Add missing ATK_VERSION_2_30
/usr/include/atk-1.0/atk/atkversion.h:379:33: error: "ATK_VERSION_2_30" is not defined, evaluates to 0 [-Werror=undef]
 #if ATK_VERSION_MIN_REQUIRED >= ATK_VERSION_2_30
                                 ^~~~~~~~~~~~~~~~
/usr/include/atk-1.0/atk/atkversion.h:387:31: error: "ATK_VERSION_2_30" is not defined, evaluates to 0 [-Werror=undef]
 #if ATK_VERSION_MAX_ALLOWED < ATK_VERSION_2_30
                               ^~~~~~~~~~~~~~~~