meson: increase minimum glib version to 2.67.4
g_spawn_async_with_pipes_and_fds was introduced in 2.67.4, so
we need to increase the minimum version in meson.build.

Failure looks like:
```
/var/tmp/portage/app-accessibility/at-spi2-core-2.44.1/work/at-spi2-core-2.44.1/build/../bus/at-spi-bus-launcher.c:349: undefined reference to `g_spawn_async_with_pipes_and_fds'
```

Bug: https://bugs.gentoo.org/850475